# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88a45493ad600cc4bbaae5dd70ed78c418012496fc95843d907387feb61676645560275e93e00b486fab0e6f0c99879a2979fd07c526ac795f21ed35e3ac3834

test:
  secret_key_base: cb537f92058609edf9156d64c21e7857a2df444aa358ff82acc68904d101dd08fbcb102271f1f4b042a9e54046185b9756b933a8c42a07016d924e601a31dfc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
